#!/usr/bin/env bash
# A Bash script that runs indefinitely and prints a message when receiving SIGTERM

# Function to handle SIGTERM
handle_term() {
    echo "I am invincible!!!"
}

# Trap SIGTERM and call handle_term
trap 'handle_term' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
