#!/usr/bin/env bash
# A Bash script that loops indefinitely and prints "I am invincible!!!" when receiving SIGTERM

# Trap SIGTERM to print message but continue running
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
