#!/usr/bin/env bash
# Display 1–20 with superstition messages using case
num=1
while [ $num -le 20 ]
do
    case $num in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$num"
            ;;
    esac
    num=$((num + 1))
done
